### ISSUE TITLE
Problem with Attestation statement format in Firefox

### ISSUE THREAD

**Issue by astec-mra** [web-auth/webauthn-framework#123]
Hello,
I use web-auth/webauthn-lib library (https://github.com/web-auth/webauthn-lib) to support FIDO2 and I am currently implementing the key registration process. When registering a token (YubiKey 5 NFC) on Google Chrome everything works fine, but on Firefox and Microsoft Edge I get this error:
"The attestation statement format "packed" is not supported.".
In the generatePublicKeyCredentialCreationOptions() method I use PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_NONE option.
$attestationObject['fmt'] variable from AttestationObjectLoader class for Chrome contains "none" and for Firefox contains "packed". I don't understand why this is happening even though PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_NONE is set.
I'm running a relying party server locally as a service.

My local configuration:
`[
    'challengeLength'       => 32,
    'timeout'               => 60000,
    'attestationConveyance' => PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_NONE,
    'userVerification'      => PublicKeyCredentialRequestOptions::USER_VERIFICATION_REQUIREMENT_DISCOURAGED,
    'authenticatorSelectionCriteria' => [
        'attachmentMode'     => AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_NO_PREFERENCE,
        'requireResidentKey' => false,
        'userVerification'   => AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED,
    ]
]`

Generated publicKey for registration process:
`PublicKeyCredentialCreationOptions(
	'rp' => PublicKeyCredentialRpEntity('my_id', 'project_name'),
	'user' => PublicKeyCredentialUserEntity('4', 'displayName', 'email'),
	'pubKeyCredParams' => [
		(seven objects PublicKeyCredentialParameters)
	],
	'excludeCredentials' => [],
	'authenticatorSelection' => AuthenticatorSelectionCriteria(
		'authenticatorAttachment' => null,
		'requireResidentKey' => false,
		'userVerification' => 'preferred'
	),
	'attestation' => 'none',
	'challenge' => '...',
	'timeout' => 60000,
	'extensions' => AuthenticationExtensionsClientInputs(
		'extensions' => []
	)
)`

Response for Chrome:
`clientDataJson => [...],
attestationObject => [
	'fmt' => 'none',
	'attStmt' => [],
	'authData' => '...'
]`

Response for Firefox:
`clientDataJson => [...],
attestationObject => [
	'fmt' => 'packed',
	'attStmt' => [
		'alg' => '-7',
		'sig' => '...',
		'x5c' => [
			0 => '...Yubico U2F Root CA Serial...'
		]
	],
	'authData' => '...'
]`

Library version: v3.1.1

I tested registration process in Firefox on https://webauthn.spomky-labs.com website and the same problem:
![image](https://user-images.githubusercontent.com/51441997/77916699-c5a97000-7299-11ea-88df-7e417daa8670.png)

EDIT:
I checked that the native method navigator.credentials.create() for setting attestation to none returns for Firefox fmt packed, so this is not a problem.

**Comment by Spomky** [comment]
Hi @astec-mra,

Thank you for the issue.
I will check what is going on.

**Comment by astec-mra** [comment]
I found the following information in the manual. If for PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_NONE option I get non-zero aaguid, the library should replace the aaguid with 16 zero bytes, set "fmt" to "none" and set the value of "attStmt" to be an empty CBOR map.

![image](https://user-images.githubusercontent.com/51441997/78126158-5c00a180-7412-11ea-9ebb-525ea17f6150.png)

Source: https://www.w3.org/TR/webauthn/#CreateCred-DetermineRpId ("If any authenticator indicates success" section, point 3.1)

**Comment by Spomky** [comment]
Thank you @astec-mra,

The library will be updated to strip tho AAGUID and attestation object if not done by the RP.

**Comment by astec-mra** [comment]
@Spomky Great, thank you very much. Do you have an approx. timeline for that?

**Comment by Spomky** [comment]
The behaviour of Firefox is really strange.
It works fine on Linux (Ubuntu), but fails on Windows  (same version of Firefox for both OS).

I don’t know when a fix will be provided.
The problem is that we need to inject the options to the `AttestationObjectLoader` object (not a big fan of that solution), or fetch the MDS in the response validator instead of the attestation loader (better design even if the attestation and the trusted anchors are not gathered at the same time).

In all cases, this means some method signatures have to be changed and therefore this will only be available in the next minor release i.e v3.2.0.

Stay tuned

**Comment by Spomky** [comment]
OK I found a solution.
It should be available by the end of the week.

**Comment by Spomky** [comment]
Should be fixed in the new branch 3.2

**Comment by michib** [comment]
@Spomky thanks for your amazing work. The error Message in the bug of nextcloud_twofactor_webauthn has changed, now it does not find the alg field of attStmt. 

```
Assert\InvalidArgumentException: The attestation statement has no key "alg".
twofactor_webauthn/vendor/beberlei/assert/lib/Assert/Assertion.php - line 1769: Assert\Assertion::createException(false, "The attesta ... .", 32, null)
twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AttestationStatement/AttestationStatement.php - line 123: Assert\Assertion::true(false, "The attesta ... .")
twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AttestationStatement/PackedAttestationStatementSupport.php - line 180: Webauthn\AttestationStatement\AttestationStatement->get("alg")
twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AttestationStatement/PackedAttestationStatementSupport.php - line 85: Webauthn\AttestationStatement\PackedAttestationStatementSupport->processWithSelfAttestation(null, Webauthn\Att ... {}, Webauthn\AuthenticatorData {})
twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AuthenticatorAttestationResponseValidator.php - line 157: Webauthn\AttestationStatement\PackedAttestationStatementSupport->isValid(null, Webauthn\Att ... {}, Webauthn\AuthenticatorData {})
```

But this can also be an issue on the side of nextcloud_twofactor_webauthn, maybe by somewrong configured things.
Unfortunately i'm currently not able to debug the issue with my hardware. But as soon as i'm able to do this, i'll let you know what's the cause. And if it's a fix for webauthn-framework, i'll provide a pr.

**Comment by Spomky** [comment]
Hi @michib,

Let me know the result on you platform. The last release works now fine with on my environment (both Windows/Linux on Chrome or Firefox).
The [demo](web-token.spomky-labs.com/) has been updated as well.

**Comment by rublon-mra** [comment]
@Spomky Thank you for updating the library.
I still have that problem during WebAuthn key registration process (where is used loadAndCheckAttestationResponse() method).
On Firefox and Microsoft Edge for YubiKey 5 NFC: "The attestation statement format "packed" is not supported." (on Chrome looks good).
This message is returning from AttestationObjectLoader class, line 80.

I removed third argument for initializing RP server and it looks as below:
$this->rpServer = new Server($rpEntity, new CredentialRepositoryService(), null);

I checked the demo (https://webauthn.spomky-labs.com) and on Firefox and Edge everything works fine, so here your patch worked - "Your account have been successfully created!".

**Comment by Spomky** [comment]
OK got it!
I was only looking for a bug in the response validator, but you are using the built-in Server class.
It is now clear for me where is the error.
It will be fixed ASAP.

**Comment by Spomky** [comment]
Hi @astec-mra,

It should be fine now with the last bug release v3.2.3

**Comment by rublon-mra** [comment]
Thank you! I checked Firefox and Edge browsers and everything works fine!
Thank you for your help and fixes.
Good job!
